### ISSUE TITLE
Running into issue while building docker image

### ISSUE THREAD

**Issue by batCoder95** [bbenzikry/spark-glue#1]
Hey @bbenzikry ,

I was going through the comment that you provided to me on this [link](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/216#issuecomment-702910709).

I was looking for ways to build a docker image with Spark, IRSA and Glue and came across this repository of yours. I am trying to build the docker image using the Dockerfile you have provided in this repository. but am running into below error while building the docker image:

`
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.40.0+dfsg-5) ...
E: Could not configure 'libc6:amd64'.
E: Could not perform immediate configuration on 'libnss-nis:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
The command '/bin/sh -c apt-get install -y git curl wget openjdk-8-jdk patch && rm -rf /var/cache/apt/*' returned a non-zero code: 100
`

Would you happen to know something about this or how I can go about investigating/resolving this?

Thanks a lot for your consideration :)

**Comment by bbenzikry** [comment]
Hi @batCoder95, I looked into this - it seems it's an issue with the upstream debian release used by the python base image. 
Look here: https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg5842443.html

I believe reverting to an older debian release as follows will just "make it work" right now

Change this line
https://github.com/bbenzikry/spark-glue/blob/b2f65994f0ab8fffb6f521a7b5ecb7ef04228e81/Dockerfile#L2

to: 
```dockerfile
FROM python:3.7-slim-stretch 
```
However, if you want to just build a spark based image, the original purpose of this repository is for post-build artifacts we use when building our spark based images. 

You can download the release directly https://github.com/bbenzikry/spark-glue/releases/download/3.0.1/spark-3.0.1-bin-hadoop-provided-glue.tgz which has the relevant glue jars and use this within your normal Spark Dockerfile. 

I think I mentioned before I'm working on a repository that outlines how to use this with EKS specifically. So while it's not completely ready for public use, I opened it up so you can have a look. It also shows how we use our patched operator ( would appreciate a :star: )

https://github.com/bbenzikry/spark-eks

**Comment by batCoder95** [comment]
Ah I see. I was under the impression that the Glue connector would have spark and hive installed within it, which is why the Dockerfile in this repository did not have spark build steps. Let me try out the "spark-eks" repository's Docker configurations, in which I notice that there are spark build steps + glue connector.

More than happy to give it a ⭐ :)

Thanks a lot for this guidance :)
